### ISSUE TITLE
A few Jungle Inferno features are still broken.

### ISSUE THREAD

**Issue by paladynne** [bw-/bwhud#12]
The only item is my custom folder is bwhud:

1. The Casual level badge on the main menu cannot be clicked.
2. The War Paint button (shortcut to preview War Paints) is missing from the Items menu.
3. The Health indicator is sometimes missing when first joining a Casual server. **hud_reload_scheme** does not fix this, but it does fix itself after respawning.
4. The "Your match is ready" prompt options cannot always be clicked:
 a. When the prompt appears after the Casual matchmaking system finds a server, neither option can be clicked.
 b. When disconnecting (bind, lost connection) from a Casual sever, the prompt options cannot be clicked: this leads to an infinite auto join loop, until you restart the game.
 c. When quickly restarting the game after disconnecting from a Casual server, the options on the prompt that appears _can_ be clicked on.

**Comment by bw-** [comment]
From the thread on tf.tv:

I haven't had much reason or motivation to update this for a long time, so sorry to you guys who've asked either here or elsewhere about changes or updates.

I've gone ahead and done as much as I really feel up to with this in regards to the Jungle Inferno update. 
Everything else should "work" but this is a fairly no-frills update to the hud. 

You can't use the new paints UI, the find game button jumps to the right side when in a server, etc. 

Maybe once people smarter than me figure out how to tweak the animations to everything I will revisit, but for now this is all I'm gonna do.
