### ISSUE TITLE
Not compatible with the current version of TF2

### ISSUE THREAD

**Issue by otmeek** [bw-/bwhud#2]
The latest update for TF2 completely changed the game's HUD and also added some changes to the file structure in custom huds. Therefore bwhud (as well as all other custom huds) no longer works.

**Comment by bw-** [comment]
https://www.dropbox.com/s/zbdv5st0ksopd2a/info.vdf?dl=0

place this file in your bwhud-master folder.

**Comment by bw-** [comment]
FIXED IT FUCK YEAH

**Comment by otmeek** [comment]
That was fast. Thanks! Still some kinks after the new update, I will open a new issue.
