### ISSUE TITLE
Crits

### ISSUE THREAD

**Issue by chostarman** [bw-/bwhud#7]
Is there are way to change the frontier justice's crits to saying 'revenge' instead of 'reven...'?

**Comment by bw-** [comment]
What resolution are you currently running?

If you are on 1920x1080 please let me know. Otherwise, you can find it in huditemeffectmeter_engineer.res.

Change HudItemEffectMeterLabel

**Comment by chostarman** [comment]
im doing 1280 by 720

**Comment by bw-** [comment]
Dang phone. 

Change ItemEffectMeterLabel's "wide" value.

**Comment by chostarman** [comment]
ok thanks
